use std::fs;
use std::path::Path;
use std::process::Command;

use assert_cmd::prelude::*;
use assert_fs::TempDir;
use predicates::prelude::*;

#[test]
fn list_discovers_seeded_skills() {
    cmd()
        .arg("list")
        .assert()
        .success()
        .stdout(predicate::str::contains("github-actions"))
        .stdout(predicate::str::contains("rust"))
        .stdout(predicate::str::contains("solidjs"));
}

#[test]
fn validate_passes_for_seeded_skills() {
    cmd()
        .arg("validate")
        .assert()
        .success()
        .stdout(predicate::str::contains("validated 3 skill(s)"));
}

#[test]
fn validate_fails_for_missing_rule_file() {
    let catalog = minimal_catalog();
    write(
        catalog.path().join("rules/missing/skill.toml"),
        r#"
name = "missing"
title = "Missing"
description = "Missing file test."

[[rules]]
title = "Missing"
file = "missing.md"
when = "Always."
"#,
    );

    cmd()
        .env("RULESKILL_CATALOG_DIR", catalog.path())
        .arg("validate")
        .assert()
        .failure()
        .stderr(predicate::str::contains("referenced file does not exist"));
}

#[test]
fn validate_rejects_rule_files_outside_rule_pack() {
    let catalog = minimal_catalog();
    write(catalog.path().join("rules/outside.md"), "# Outside\n");
    write(
        catalog.path().join("rules/escape/skill.toml"),
        r#"
name = "escape"
title = "Escape"
description = "Traversal test."

[[rules]]
title = "Outside"
file = "../outside.md"
when = "Always."
"#,
    );

    cmd()
        .env("RULESKILL_CATALOG_DIR", catalog.path())
        .arg("validate")
        .assert()
        .failure()
        .stderr(predicate::str::contains(
            "must stay inside the skill folder",
        ));
}

#[test]
fn validate_fails_for_invalid_names() {
    let catalog = minimal_catalog();
    write(
        catalog.path().join("rules/not-rust/skill.toml"),
        r#"
name = "RustRules"
title = "Rust Rules"
description = "Invalid name test."

[[rules]]
title = "Rule"
file = "rule.md"
when = "Always."
"#,
    );
    write(catalog.path().join("rules/not-rust/rule.md"), "# Rule\n");

    cmd()
        .env("RULESKILL_CATALOG_DIR", catalog.path())
        .arg("validate")
        .assert()
        .failure()
        .stderr(predicate::str::contains("must match folder"))
        .stderr(predicate::str::contains("must be kebab-case"));
}

#[test]
fn validate_fails_for_duplicate_output_references() {
    let catalog = minimal_catalog();
    write(
        catalog.path().join("rules/dupes/skill.toml"),
        r#"
name = "dupes"
title = "Dupes"
description = "Duplicate output test."

[[rules]]
title = "First"
file = "first/shared.md"
when = "Always."

[[rules]]
title = "Second"
file = "second/shared.md"
when = "Always."
"#,
    );
    write(
        catalog.path().join("rules/dupes/first/shared.md"),
        "# First\n",
    );
    write(
        catalog.path().join("rules/dupes/second/shared.md"),
        "# Second\n",
    );

    cmd()
        .env("RULESKILL_CATALOG_DIR", catalog.path())
        .arg("validate")
        .assert()
        .failure()
        .stderr(predicate::str::contains("duplicate output reference path"));
}

#[test]
fn validate_fails_for_empty_rule_lists() {
    let catalog = minimal_catalog();
    write(
        catalog.path().join("rules/empty/skill.toml"),
        r#"
name = "empty"
title = "Empty"
description = "Empty rules test."
"#,
    );

    cmd()
        .env("RULESKILL_CATALOG_DIR", catalog.path())
        .arg("validate")
        .assert()
        .failure()
        .stderr(predicate::str::contains(
            "at least one [[rules]] entry is required",
        ));
}

#[test]
fn install_rust_to_codex_writes_skill_and_references() {
    let repo = TempDir::new().unwrap();

    cmd()
        .current_dir(repo.path())
        .args(["install", "rust", "--target", "codex"])
        .assert()
        .success()
        .stdout(predicate::str::contains("wrote"));

    let skill_path = repo.path().join(".agents/skills/rust-rules/SKILL.md");
    assert_file_starts_with(
        &skill_path,
        "---\nname: rust-rules\ndescription: \"Use for Rust implementation",
    );
    assert_file_contains(&skill_path, "Rust Rules");
    assert_file_does_not_contain(&skill_path, "Generated by ruleskill");
    assert_eq!(
        reference_count(repo.path().join(".agents/skills/rust-rules/references")),
        10
    );
    assert_file_does_not_contain(
        repo.path()
            .join(".agents/skills/rust-rules/references/rust-api-design.md"),
        "Generated by ruleskill",
    );
}

#[test]
fn install_rust_to_claude_writes_skill_and_references() {
    let repo = TempDir::new().unwrap();

    cmd()
        .current_dir(repo.path())
        .args(["install", "rust", "--target", "claude"])
        .assert()
        .success();

    let skill_path = repo.path().join(".claude/skills/rust-rules/SKILL.md");
    assert_file_starts_with(
        &skill_path,
        "---\nname: rust-rules\ndescription: \"Use for Rust implementation",
    );
    assert_file_contains(&skill_path, "Rust Rules");
    assert_eq!(
        reference_count(repo.path().join(".claude/skills/rust-rules/references")),
        10
    );
}

#[test]
fn install_github_actions_to_all_writes_both_harness_outputs() {
    let repo = TempDir::new().unwrap();

    cmd()
        .current_dir(repo.path())
        .args(["install", "github-actions", "--target", "all"])
        .assert()
        .success();

    assert_file_contains(
        repo.path()
            .join(".agents/skills/github-actions-rules/SKILL.md"),
        "GitHub Actions Rules",
    );
    assert_file_contains(
        repo.path()
            .join(".claude/skills/github-actions-rules/SKILL.md"),
        "GitHub Actions Rules",
    );
}

#[test]
fn auto_detection_installs_every_detected_harness() {
    let repo = TempDir::new().unwrap();
    fs::create_dir_all(repo.path().join(".agents")).unwrap();
    fs::create_dir_all(repo.path().join(".claude")).unwrap();

    cmd()
        .current_dir(repo.path())
        .args(["install", "github-actions"])
        .assert()
        .success();

    assert!(repo
        .path()
        .join(".agents/skills/github-actions-rules/SKILL.md")
        .is_file());
    assert!(repo
        .path()
        .join(".claude/skills/github-actions-rules/SKILL.md")
        .is_file());
}

#[test]
fn auto_detection_errors_when_no_harness_is_found() {
    let repo = TempDir::new().unwrap();

    cmd()
        .current_dir(repo.path())
        .args(["install", "rust"])
        .assert()
        .failure()
        .stderr(predicate::str::contains("no supported harness detected"))
        .stderr(predicate::str::contains("--target codex"));
}

#[test]
fn existing_destinations_are_overwritten_without_force() {
    let repo = TempDir::new().unwrap();
    let destination = repo.path().join(".agents/skills/rust-rules/SKILL.md");
    write(&destination, "manual skill\n");

    cmd()
        .current_dir(repo.path())
        .args(["install", "rust", "--target", "codex"])
        .assert()
        .success();

    assert_file_contains(&destination, "name: rust-rules");
    assert_file_does_not_contain(&destination, "manual skill");
}

#[test]
fn dry_run_reports_paths_without_writing() {
    let repo = TempDir::new().unwrap();

    cmd()
        .current_dir(repo.path())
        .args(["install", "rust", "--target", "codex", "--dry-run"])
        .assert()
        .success()
        .stdout(predicate::str::contains("would write"))
        .stdout(predicate::str::contains("rust-rules"))
        .stdout(predicate::str::contains("SKILL.md"));

    assert!(!repo.path().join(".agents").exists());
}

#[test]
fn new_catalog_fixture_appears_in_list_without_code_changes() {
    let catalog = minimal_catalog();
    write(
        catalog.path().join("rules/react/skill.toml"),
        r#"
name = "react"
title = "React Rules"
description = "React test skill."

[[rules]]
title = "Components"
file = "components.md"
when = "Read when editing components."
"#,
    );
    write(
        catalog.path().join("rules/react/components.md"),
        "# Components\n",
    );

    cmd()
        .env("RULESKILL_CATALOG_DIR", catalog.path())
        .arg("list")
        .assert()
        .success()
        .stdout(predicate::str::contains("react"));
}

#[test]
fn install_renders_paths_frontmatter_only_when_set() {
    let catalog = paths_template_catalog();
    write(
        catalog.path().join("rules/with-paths/skill.toml"),
        r#"
name = "with-paths"
title = "With Paths"
description = "Paths test skill."
paths = "**/*.tsx,**/*.ts"

[[rules]]
title = "Example"
file = "example.md"
when = "Read when relevant."
"#,
    );
    write(catalog.path().join("rules/with-paths/example.md"), "# Ex\n");
    write(
        catalog.path().join("rules/without-paths/skill.toml"),
        r#"
name = "without-paths"
title = "Without Paths"
description = "No paths test skill."

[[rules]]
title = "Example"
file = "example.md"
when = "Read when relevant."
"#,
    );
    write(
        catalog.path().join("rules/without-paths/example.md"),
        "# Ex\n",
    );

    let repo = TempDir::new().unwrap();
    for pack in ["with-paths", "without-paths"] {
        cmd()
            .env("RULESKILL_CATALOG_DIR", catalog.path())
            .current_dir(repo.path())
            .args(["install", pack, "--target", "claude"])
            .assert()
            .success();
    }

    assert_file_starts_with(
        repo.path().join(".claude/skills/with-paths-rules/SKILL.md"),
        "---\nname: with-paths-rules\ndescription: \"Paths test skill.\"\npaths: \"**/*.tsx,**/*.ts\"\n---",
    );
    assert_file_does_not_contain(
        repo.path()
            .join(".claude/skills/without-paths-rules/SKILL.md"),
        "paths:",
    );
}

#[test]
fn validate_fails_for_blank_paths() {
    let catalog = minimal_catalog();
    write(
        catalog.path().join("rules/blank-paths/skill.toml"),
        r#"
name = "blank-paths"
title = "Blank Paths"
description = "Blank paths test."
paths = "  "

[[rules]]
title = "Example"
file = "example.md"
when = "Read when relevant."
"#,
    );
    write(
        catalog.path().join("rules/blank-paths/example.md"),
        "# Ex\n",
    );

    cmd()
        .env("RULESKILL_CATALOG_DIR", catalog.path())
        .arg("validate")
        .assert()
        .failure()
        .stderr(predicate::str::contains("paths must be non-empty when set"));
}

#[test]
fn install_without_skill_lists_available_packs() {
    let catalog = minimal_catalog();
    seed_pack(&catalog, "rust");
    seed_pack(&catalog, "github-actions");

    cmd()
        .env("RULESKILL_CATALOG_DIR", catalog.path())
        .arg("install")
        .assert()
        .failure()
        .stderr(predicate::str::contains("no skill provided"))
        .stderr(predicate::str::contains("rust"))
        .stderr(predicate::str::contains("github-actions"));
}

#[test]
fn install_unknown_skill_suggests_closest() {
    let catalog = minimal_catalog();
    seed_pack(&catalog, "github-actions");

    cmd()
        .env("RULESKILL_CATALOG_DIR", catalog.path())
        .args(["install", "github-action"])
        .assert()
        .failure()
        .stderr(predicate::str::contains(
            "unknown skill 'github-action'. Did you mean 'github-actions'?",
        ));
}

#[test]
fn install_unknown_skill_without_close_match() {
    let catalog = minimal_catalog();
    seed_pack(&catalog, "github-actions");

    cmd()
        .env("RULESKILL_CATALOG_DIR", catalog.path())
        .args(["install", "totally-different"])
        .assert()
        .failure()
        .stderr(predicate::str::contains(
            "unknown skill 'totally-different'",
        ))
        .stderr(predicate::str::contains("ruleskill list"))
        .stderr(predicate::str::contains("Did you mean").not());
}

fn cmd() -> Command {
    Command::cargo_bin("ruleskill").unwrap()
}

fn seed_pack(catalog: &TempDir, name: &str) {
    write(
        catalog.path().join(format!("rules/{name}/skill.toml")),
        &format!(
            r#"
name = "{name}"
title = "{name} Rules"
description = "{name} test skill."

[[rules]]
title = "Example"
file = "example.md"
when = "Read when relevant."
"#
        ),
    );
}

fn minimal_catalog() -> TempDir {
    let catalog = TempDir::new().unwrap();
    write(
        catalog.path().join("templates/skill.md.j2"),
        r"---
name: {{ output_name }}
description: {{ description_yaml }}
---

# {{ title }}

{{ description }}

{% for rule in rules -%}
- {{ rule.title }}: references/{{ rule.reference_file }}
{% endfor %}
",
    );
    fs::create_dir_all(catalog.path().join("rules")).unwrap();
    catalog
}

fn paths_template_catalog() -> TempDir {
    let catalog = TempDir::new().unwrap();
    write(
        catalog.path().join("templates/skill.md.j2"),
        r"---
name: {{ output_name }}
description: {{ description_yaml }}
{%- if paths_yaml %}
paths: {{ paths_yaml }}
{%- endif %}
---

# {{ title }}
",
    );
    fs::create_dir_all(catalog.path().join("rules")).unwrap();
    catalog
}

fn write(path: impl AsRef<Path>, contents: &str) {
    let path = path.as_ref();
    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent).unwrap();
    }
    fs::write(path, contents).unwrap();
}

fn assert_file_contains(path: impl AsRef<Path>, expected: &str) {
    let contents = fs::read_to_string(path).unwrap();
    assert!(
        contents.contains(expected),
        "expected file to contain {expected:?}, got:\n{contents}"
    );
}

fn assert_file_does_not_contain(path: impl AsRef<Path>, unexpected: &str) {
    let contents = fs::read_to_string(path).unwrap();
    assert!(
        !contents.contains(unexpected),
        "expected file not to contain {unexpected:?}, got:\n{contents}"
    );
}

fn assert_file_starts_with(path: impl AsRef<Path>, expected: &str) {
    let contents = fs::read_to_string(path).unwrap();
    assert!(
        contents.starts_with(expected),
        "expected file to start with {expected:?}, got:\n{contents}"
    );
}

fn reference_count(path: impl AsRef<Path>) -> usize {
    fs::read_dir(path).unwrap().count()
}
