use std::fs;
use std::path::Path;
use std::process::Command;

use assert_cmd::prelude::*;
use assert_fs::TempDir;
use predicates::prelude::*;

const MARKER: &str = "<!-- Generated by ruleskill. Do not edit directly. -->";

#[test]
fn list_discovers_seeded_skills() {
    cmd()
        .arg("list")
        .assert()
        .success()
        .stdout(predicate::str::contains("github-actions"))
        .stdout(predicate::str::contains("rust"));
}

#[test]
fn validate_passes_for_seeded_skills() {
    cmd()
        .arg("validate")
        .assert()
        .success()
        .stdout(predicate::str::contains("validated 2 skill(s)"));
}

#[test]
fn validate_fails_for_missing_rule_file() {
    let catalog = minimal_catalog();
    write(
        catalog.path().join("rules/missing/skill.toml"),
        r#"
name = "missing"
title = "Missing"
description = "Missing file test."

[[rules]]
title = "Missing"
file = "missing.md"
when = "Always."
"#,
    );

    cmd()
        .env("RULESKILL_CATALOG_DIR", catalog.path())
        .arg("validate")
        .assert()
        .failure()
        .stderr(predicate::str::contains("referenced file does not exist"));
}

#[test]
fn validate_fails_for_invalid_names() {
    let catalog = minimal_catalog();
    write(
        catalog.path().join("rules/not-rust/skill.toml"),
        r#"
name = "RustRules"
title = "Rust Rules"
description = "Invalid name test."

[[rules]]
title = "Rule"
file = "rule.md"
when = "Always."
"#,
    );
    write(catalog.path().join("rules/not-rust/rule.md"), "# Rule\n");

    cmd()
        .env("RULESKILL_CATALOG_DIR", catalog.path())
        .arg("validate")
        .assert()
        .failure()
        .stderr(predicate::str::contains("must match folder"))
        .stderr(predicate::str::contains("must be kebab-case"));
}

#[test]
fn validate_fails_for_duplicate_output_references() {
    let catalog = minimal_catalog();
    write(
        catalog.path().join("rules/dupes/skill.toml"),
        r#"
name = "dupes"
title = "Dupes"
description = "Duplicate output test."

[[rules]]
title = "First"
file = "first/shared.md"
when = "Always."

[[rules]]
title = "Second"
file = "second/shared.md"
when = "Always."
"#,
    );
    write(
        catalog.path().join("rules/dupes/first/shared.md"),
        "# First\n",
    );
    write(
        catalog.path().join("rules/dupes/second/shared.md"),
        "# Second\n",
    );

    cmd()
        .env("RULESKILL_CATALOG_DIR", catalog.path())
        .arg("validate")
        .assert()
        .failure()
        .stderr(predicate::str::contains("duplicate output reference path"));
}

#[test]
fn validate_fails_for_empty_rule_lists() {
    let catalog = minimal_catalog();
    write(
        catalog.path().join("rules/empty/skill.toml"),
        r#"
name = "empty"
title = "Empty"
description = "Empty rules test."
"#,
    );

    cmd()
        .env("RULESKILL_CATALOG_DIR", catalog.path())
        .arg("validate")
        .assert()
        .failure()
        .stderr(predicate::str::contains(
            "at least one [[rules]] entry is required",
        ));
}

#[test]
fn install_rust_to_codex_writes_skill_and_references() {
    let repo = TempDir::new().unwrap();

    cmd()
        .current_dir(repo.path())
        .args(["install", "rust", "--target", "codex"])
        .assert()
        .success()
        .stdout(predicate::str::contains("wrote"));

    assert_file_contains(
        repo.path().join(".agents/skills/rust/SKILL.md"),
        "Rust Rules",
    );
    assert_eq!(
        reference_count(repo.path().join(".agents/skills/rust/references")),
        10
    );
}

#[test]
fn install_rust_to_claude_writes_skill_and_references() {
    let repo = TempDir::new().unwrap();

    cmd()
        .current_dir(repo.path())
        .args(["install", "rust", "--target", "claude"])
        .assert()
        .success();

    assert_file_contains(
        repo.path().join(".claude/skills/rust/SKILL.md"),
        "Rust Rules",
    );
    assert_eq!(
        reference_count(repo.path().join(".claude/skills/rust/references")),
        10
    );
}

#[test]
fn install_github_actions_to_all_writes_both_harness_outputs() {
    let repo = TempDir::new().unwrap();

    cmd()
        .current_dir(repo.path())
        .args(["install", "github-actions", "--target", "all"])
        .assert()
        .success();

    assert_file_contains(
        repo.path().join(".agents/skills/github-actions/SKILL.md"),
        "GitHub Actions Rules",
    );
    assert_file_contains(
        repo.path().join(".claude/skills/github-actions/SKILL.md"),
        "GitHub Actions Rules",
    );
}

#[test]
fn auto_detection_installs_every_detected_harness() {
    let repo = TempDir::new().unwrap();
    fs::create_dir_all(repo.path().join(".agents")).unwrap();
    fs::create_dir_all(repo.path().join(".claude")).unwrap();

    cmd()
        .current_dir(repo.path())
        .args(["install", "github-actions"])
        .assert()
        .success();

    assert!(repo
        .path()
        .join(".agents/skills/github-actions/SKILL.md")
        .is_file());
    assert!(repo
        .path()
        .join(".claude/skills/github-actions/SKILL.md")
        .is_file());
}

#[test]
fn auto_detection_errors_when_no_harness_is_found() {
    let repo = TempDir::new().unwrap();

    cmd()
        .current_dir(repo.path())
        .args(["install", "rust"])
        .assert()
        .failure()
        .stderr(predicate::str::contains("no supported harness detected"))
        .stderr(predicate::str::contains("--target codex"));
}

#[test]
fn non_generated_destinations_are_protected_unless_forced() {
    let repo = TempDir::new().unwrap();
    let destination = repo.path().join(".agents/skills/rust/SKILL.md");
    write(&destination, "manual skill\n");

    cmd()
        .current_dir(repo.path())
        .args(["install", "rust", "--target", "codex"])
        .assert()
        .failure()
        .stderr(predicate::str::contains(
            "refusing to overwrite non-generated file",
        ));

    cmd()
        .current_dir(repo.path())
        .args(["install", "rust", "--target", "codex", "--force"])
        .assert()
        .success();
    assert_file_contains(destination, MARKER);
}

#[test]
fn dry_run_reports_paths_without_writing() {
    let repo = TempDir::new().unwrap();

    cmd()
        .current_dir(repo.path())
        .args(["install", "rust", "--target", "codex", "--dry-run"])
        .assert()
        .success()
        .stdout(predicate::str::contains("would write"))
        .stdout(predicate::str::contains("SKILL.md"));

    assert!(!repo.path().join(".agents").exists());
}

#[test]
fn new_catalog_fixture_appears_in_list_without_code_changes() {
    let catalog = minimal_catalog();
    write(
        catalog.path().join("rules/react/skill.toml"),
        r#"
name = "react"
title = "React Rules"
description = "React test skill."

[[rules]]
title = "Components"
file = "components.md"
when = "Read when editing components."
"#,
    );
    write(
        catalog.path().join("rules/react/components.md"),
        "# Components\n",
    );

    cmd()
        .env("RULESKILL_CATALOG_DIR", catalog.path())
        .arg("list")
        .assert()
        .success()
        .stdout(predicate::str::contains("react"));
}

fn cmd() -> Command {
    Command::cargo_bin("ruleskill").unwrap()
}

fn minimal_catalog() -> TempDir {
    let catalog = TempDir::new().unwrap();
    write(
        catalog.path().join("templates/skill.md.j2"),
        r#"<!-- Generated by ruleskill. Do not edit directly. -->

# {{ title }}

{{ description }}

{% for rule in rules -%}
- {{ rule.title }}: references/{{ rule.reference_file }}
{% endfor %}
"#,
    );
    fs::create_dir_all(catalog.path().join("rules")).unwrap();
    catalog
}

fn write(path: impl AsRef<Path>, contents: &str) {
    let path = path.as_ref();
    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent).unwrap();
    }
    fs::write(path, contents).unwrap();
}

fn assert_file_contains(path: impl AsRef<Path>, expected: &str) {
    let contents = fs::read_to_string(path).unwrap();
    assert!(
        contents.contains(expected),
        "expected file to contain {expected:?}, got:\n{contents}"
    );
}

fn reference_count(path: impl AsRef<Path>) -> usize {
    fs::read_dir(path).unwrap().count()
}
