use anyhow::{ensure, Context, Result};
use minijinja::Environment;

use crate::catalog::RenderSkill;

pub const GENERATED_MARKER: &str = "<!-- Generated by ruleskill. Do not edit directly. -->";

pub fn render_skill(template: &str, skill: &RenderSkill) -> Result<String> {
    let mut env = Environment::new();
    env.add_template("skill.md.j2", template)
        .context("failed to load skill template")?;
    let rendered = env
        .get_template("skill.md.j2")
        .context("failed to resolve skill template")?
        .render(skill)
        .context("failed to render skill template")?;

    ensure!(
        rendered.trim_start().starts_with(GENERATED_MARKER),
        "template output must start with the generated marker"
    );

    Ok(rendered)
}

pub fn generated_reference(source: &str) -> String {
    format!("{GENERATED_MARKER}\n\n{source}")
}
